### PR TITLE
Clean up

### PR DESCRIPTION
**Pull request by brunocodutra**
* Removed broken integration to RealFaviconGenerator
* Removed build artifacts from git
* Improved automated tests to check generated assets against known fixtures
* Updated dependencies

Since the online generation feature has been removed we have to bump the major version

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@brunocodutra feel free to merge and ping me i am give your right to npm

**Comment by brunocodutra** [comment]
@evilebottnawi thanks!

How do we coordinate publishing to npm?

**Comment by evilebottnawi** [comment]
@brunocodutra send me your npm username on email sheo13666q@gmail.com

**Comment by evilebottnawi** [comment]
@brunocodutra done, try to release :+1:

**Comment by evilebottnawi** [comment]
@brunocodutra wait

**Comment by evilebottnawi** [comment]
@brunocodutra we will major release?

**Comment by brunocodutra** [comment]
@evilebottnawi I believe we have to, since there's a breaking change in that a feature was removed

**Comment by evilebottnawi** [comment]
@brunocodutra good, let's fix license field https://github.com/evilebottnawi/favicons/blob/master/package.json#L26 to MIT (now we have one license in package and other in project) and feel free to release :+1:

**Pull request merged**
