### PR TITLE
Migrate tests to Ava

### PR DESCRIPTION
**Pull request by brunocodutra**
relates to #205

### CODE REVIEW

**Comment by brunocodutra** [comment]
@evilebottnawi I'll add code coverage report with this PR before getting it merged

**Comment by evilebottnawi** [comment]
@brunocodutra let's always use `npm@5` in tests and use `npm ci`

**Comment by evilebottnawi** [comment]
` npm i -g npm@5`

**Comment by brunocodutra** [comment]
@evilebottnawi should I commit `package-lock.json` as well then?

**Comment by evilebottnawi** [comment]
@brunocodutra yes, lock file always should be in repo

**Comment by brunocodutra** [comment]
@evilebottnawi for some reason `npm ci` doesn't fly on travis, it chokes on `prepublish` because appearently `gulp` is not installed, any idea what's going wrong?

https://travis-ci.org/evilebottnawi/favicons/jobs/360218204#L462

**Comment by evilebottnawi** [comment]
very strange, seems npm bug, let's install gulp manually after `npm ci`

**Comment by brunocodutra** [comment]
@evilebottnawi oh wait, that won't work, because `prepublish` runs just after `npm ci`, so installing it afterwards won't help. 

I guess I'll have to fall back to `npm install`?

**Comment by evilebottnawi** [comment]
@brunocodutra hm, let's use `npm install` before we migrate from gulp, we can rewrite stream tests without gulp

**Comment by brunocodutra** [comment]
@evilebottnawi CI finally passed, could you take a look at it again?

**Pull request merged**
